// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMi-isVBu1D6m9WwVG8LAFOAYE9-04RA',
    appId: '1:573893453432:web:c9c53fd0c19a6cb5acaf8d',
    messagingSenderId: '573893453432',
    projectId: 'uas-praktikum-46d0e',
    authDomain: 'uas-praktikum-46d0e.firebaseapp.com',
    storageBucket: 'uas-praktikum-46d0e.appspot.com',
    measurementId: 'G-08YZFFJ067',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLnh8jvPM_ei8II_FNhcs_2AeZRND6u4',
    appId: '1:573893453432:android:fbaeec12ed59e9b4acaf8d',
    messagingSenderId: '573893453432',
    projectId: 'uas-praktikum-46d0e',
    storageBucket: 'uas-praktikum-46d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mK4aM2FIyYX0gsp8uecjFLT6dKqhmd0',
    appId: '1:573893453432:ios:1688cfa1b127a85eacaf8d',
    messagingSenderId: '573893453432',
    projectId: 'uas-praktikum-46d0e',
    storageBucket: 'uas-praktikum-46d0e.appspot.com',
    iosClientId: '573893453432-78190qqr4ueadjbgpfqfo4jd1bjah13g.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mK4aM2FIyYX0gsp8uecjFLT6dKqhmd0',
    appId: '1:573893453432:ios:1688cfa1b127a85eacaf8d',
    messagingSenderId: '573893453432',
    projectId: 'uas-praktikum-46d0e',
    storageBucket: 'uas-praktikum-46d0e.appspot.com',
    iosClientId: '573893453432-78190qqr4ueadjbgpfqfo4jd1bjah13g.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumFirebaseLogin',
  );
}
